---
services:
  checklist_site:
    container_name: checklist_site
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - main_sites

networks:
  main_sites:
    external: true
