---
name: CI-Lint

on:
  push:
    branches: [main]
    paths:
      - "app/**"
      - "components/**"
      - "hooks/**"
      - "lib/**"
      - "public/**"
      - "types/**"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run ESLint
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm run lint

  tsc:
    runs-on: ubuntu-latest
    name: Run Typechecker
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm run typecheck
